"""
database/models.py

SQLAlchemy ORM base and reusable mixins for PartnerOS.

This module intentionally defines only foundational infrastructure --
the declarative `Base` class and common mixins -- and NOT yet any concrete
domain tables (e.g. cTrader-related models are explicitly out of scope per
current requirements). Future model files/modules should import `Base` and
the mixins from here rather than redefining declarative bases elsewhere,
keeping a single shared metadata registry for Alembic migrations.
"""

from __future__ import annotations

from datetime import datetime, timezone
import uuid

from sqlalchemy import DateTime, MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# A consistent naming convention for constraints/indexes makes autogenerated
# Alembic migrations deterministic and avoids "unnamed constraint" errors
# on backends (like PostgreSQL) that require explicit names for certain
# DDL operations.
_NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """
    Shared declarative base for all ORM models in PartnerOS.

    All future model modules (e.g. for cTrader integrations, partner
    records, transactions, etc.) should subclass this `Base` so that they
    share a single `MetaData` registry, which Alembic relies on to detect
    schema changes correctly.
    """

    metadata = MetaData(naming_convention=_NAMING_CONVENTION)


def _utcnow() -> datetime:
    """Return the current UTC time as a timezone-aware datetime."""
    return datetime.now(timezone.utc)


class UUIDPrimaryKeyMixin:
    """
    Mixin providing a UUID primary key column.

    Using a UUID (rather than an auto-incrementing integer) avoids
    collisions across distributed inserts and prevents leaking row counts
    or insertion order through public-facing identifiers.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        primary_key=True,
        default=uuid.uuid4,
        nullable=False,
    )


class TimestampMixin:
    """
    Mixin providing `created_at` / `updated_at` audit columns.

    `created_at` is set once at insert time; `updated_at` is refreshed on
    every update via the `onupdate` callback, giving every model basic
    audit-trail support with zero per-model boilerplate.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=_utcnow,
        onupdate=_utcnow,
        nullable=False,
    )


async def init_models() -> None:
    """
    Create all tables registered on `Base.metadata`.

    Intended for local development / first-run bootstrapping with SQLite.
    For production deployments, schema changes should instead be managed
    via Alembic migrations (not yet configured in this foundation layer).

    This function deliberately imports `get_engine` locally to avoid a
    circular import between `database.engine` and `database.models` at
    module load time.
    """
    from database.engine import get_engine

    engine = get_engine()
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
